### ISSUE TITLE
error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by tianke0711** [chakki-works/seqeval#103]
pip install seqeval
Collecting seqeval
  Using cached seqeval-1.2.2.tar.gz (43 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]
      /home/jupyter/.local/lib/python3.7/site-packages/setuptools-68.0.0-py3.7.egg/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        File "/home/jupyter/.local/lib/python3.7/site-packages/setuptools-68.0.0-py3.7.egg/pkg_resources/__init__.py", line 3109, in _dep_map
          return self.__dep_map
        File "/home/jupyter/.local/lib/python3.7/site-packages/setuptools-68.0.0-py3.7.egg/pkg_resources/__init__.py", line 2902, in __getattr__
          raise AttributeError(attr)
      AttributeError: _DistInfoDistribution__dep_map
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/jupyter/.local/lib/python3.7/site-packages/setuptools-68.0.0-py3.7.egg/pkg_resources/__init__.py", line 3100, in _parsed_pkg_info
          return self._pkg_info
        File "/home/jupyter/.local/lib/python3.7/site-packages/setuptools-68.0.0-py3.7.egg/pkg_resources/__init__.py", line 2902, in __getattr__
          raise AttributeError(attr)
      AttributeError: _pkg_info
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/var/tmp/pip-install-_7jn6sk2/seqeval_3394686b0ab54957bf8b73cc5117ed9c/setup.py", line 56, in <module>
          'Programming Language :: Python :: Implementation :: PyPy'
        File "/home/jupyter/.local/lib/python3.7/site-packages/setuptools-68.0.0-py3.7.egg/setuptools/__init__.py", line 106, in setup
          _install_setup_requires(attrs)
        File "/home/jupyter/.local/lib/python3.7/site-packages/setuptools-68.0.0-py3.7.egg/setuptools/__init__.py", line 79, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/home/jupyter/.local/lib/python3.7/site-packages/setuptools-68.0.0-py3.7.egg/setuptools/__init__.py", line 84, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/home/jupyter/.local/lib/python3.7/site-packages/setuptools-68.0.0-py3.7.egg/setuptools/dist.py", line 907, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/home/jupyter/.local/lib/python3.7/site-packages/setuptools-68.0.0-py3.7.egg/setuptools/installer.py", line 41, in _fetch_build_eggs
          replace_conflicting=True,
        File "/home/jupyter/.local/lib/python3.7/site-packages/setuptools-68.0.0-py3.7.egg/pkg_resources/__init__.py", line 834, in resolve
          new_requirements = dist.requires(req.extras)[::-1]
        File "/home/jupyter/.local/lib/python3.7/site-packages/setuptools-68.0.0-py3.7.egg/pkg_resources/__init__.py", line 2822, in requires
          dm = self._dep_map
        File "/home/jupyter/.local/lib/python3.7/site-packages/setuptools-68.0.0-py3.7.egg/pkg_resources/__init__.py", line 3111, in _dep_map
          self.__dep_map = self._compute_dependencies()
        File "/home/jupyter/.local/lib/python3.7/site-packages/setuptools-68.0.0-py3.7.egg/pkg_resources/__init__.py", line 3120, in _compute_dependencies
          for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
        File "/home/jupyter/.local/lib/python3.7/site-packages/setuptools-68.0.0-py3.7.egg/pkg_resources/__init__.py", line 3102, in _parsed_pkg_info
          metadata = self.get_metadata(self.PKG_INFO)
        File "/home/jupyter/.local/lib/python3.7/site-packages/setuptools-68.0.0-py3.7.egg/pkg_resources/__init__.py", line 1519, in get_metadata
          value = self._get(path)
        File "/home/jupyter/.local/lib/python3.7/site-packages/setuptools-68.0.0-py3.7.egg/pkg_resources/__init__.py", line 1727, in _get
          with open(path, 'rb') as stream:
      FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.7/site-packages/typing_extensions-4.5.0.dist-info/METADATA'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
---------

```bash
# copy-paste the error message here
```

Your Environment
---------

*   Operating System:
*   Python Version:
*   Package Version:

**Comment by tianke0711** [comment]
1. Operating System: ebian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
2. Python Version: Python 3.7.12
3. Package Version:
