### ISSUE TITLE
Installation on GitHub `windows-latest` randomly fails

### ISSUE THREAD

**Issue by anakin87** [chakki-works/seqeval#104]
How to reproduce the problem
---------
The installation of `seqeval==1.2.2` randomly fails on GitHub CI (using `windows-latest`).

<details><summary>Error message</summary>

> Collecting seqeval (from farm-haystack==1.22.0rc0)
>   Downloading seqeval-1.2.2.tar.gz (43 kB)
>      ---------------------------------------- 43.6/43.6 kB 2.1 MB/s eta 0:00:00
>   Installing build dependencies: started
>   Installing build dependencies: finished with status 'done'
>   Getting requirements to build wheel: started
>   Getting requirements to build wheel: finished with status 'done'
>   Installing backend dependencies: started
>   Installing backend dependencies: finished with status 'done'
>   Preparing metadata (pyproject.toml): started
>   Preparing metadata (pyproject.toml): finished with status 'error'
>   error: subprocess-exited-with-error
>   
>   Preparing metadata (pyproject.toml) did not run successfully.
>   exit code: 1
>   
>   [61 lines of output]
>   running dist_info
>   creating C:\Users\runneradmin\AppData\Local\Temp\pip-modern-metadata-q15h8b2q\seqeval.egg-info
>   writing C:\Users\runneradmin\AppData\Local\Temp\pip-modern-metadata-q15h8b2q\seqeval.egg-info\PKG-INFO
>   writing dependency_links to C:\Users\runneradmin\AppData\Local\Temp\pip-modern-metadata-q15h8b2q\seqeval.egg-info\dependency_links.txt
>   writing requirements to C:\Users\runneradmin\AppData\Local\Temp\pip-modern-metadata-q15h8b2q\seqeval.egg-info\requires.txt
>   writing top-level names to C:\Users\runneradmin\AppData\Local\Temp\pip-modern-metadata-q15h8b2q\seqeval.egg-info\top_level.txt
>   writing manifest file 'C:\Users\runneradmin\AppData\Local\Temp\pip-modern-metadata-q15h8b2q\seqeval.egg-info\SOURCES.txt'
>   ERROR setuptools_scm._file_finders.git listing git files failed - pretending there aren't any
>   Traceback (most recent call last):
>     File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
>       main()
>     File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
>       json_out['return_val'] = hook(**hook_input['kwargs'])
>     File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
>       return hook(metadata_directory, config_settings)
>     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-2h3whv_b\overlay\Lib\site-packages\setuptools\build_meta.py", line 396, in prepare_metadata_for_build_wheel
>       self.run_setup()
>     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-2h3whv_b\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
>       super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
>     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-2h3whv_b\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
>       exec(code, locals())
>     File "<string>", line 27, in <module>
>     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-2h3whv_b\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
>       return distutils.core.setup(**attrs)
>     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-2h3whv_b\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
>       return run_commands(dist)
>     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-2h3whv_b\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
>       dist.run_commands()
>     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-2h3whv_b\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
>       self.run_command(cmd)
>     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-2h3whv_b\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
>       super().run_command(command)
>     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-2h3whv_b\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>       cmd_obj.run()
>     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-2h3whv_b\overlay\Lib\site-packages\setuptools\command\dist_info.py", line 107, in run
>       self.egg_info.run()
>     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-2h3whv_b\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 318, in run
>       self.find_sources()
>     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-2h3whv_b\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 326, in find_sources
>       mm.run()
>     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-2h3whv_b\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 548, in run
>       self.add_defaults()
>     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-2h3whv_b\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 589, in add_defaults
>       rcfiles = list(walk_revctrl())
>     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-2h3whv_b\overlay\Lib\site-packages\setuptools\command\sdist.py", line 18, in walk_revctrl
>       for item in ep.load()(dirname):
>     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-2h3whv_b\normal\Lib\site-packages\setuptools_scm\_file_finders\__init__.py", line 103, in find_files
>       res: list[str] = command(path)
>     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-2h3whv_b\normal\Lib\site-packages\setuptools_scm\_file_finders\hg.py", line 50, in hg_find_files
>       toplevel = _hg_toplevel(path)
>     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-2h3whv_b\normal\Lib\site-packages\setuptools_scm\_file_finders\hg.py", line 18, in _hg_toplevel
>       res = _run(
>     File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-2h3whv_b\normal\Lib\site-packages\setuptools_scm\_run_cmd.py", line 138, in run
>       res = subprocess.run(
>     File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\subprocess.py", line 495, in run
>       stdout, stderr = process.communicate(input, timeout=timeout)
>     File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\subprocess.py", line 1028, in communicate
>       stdout, stderr = self._communicate(input, endtime, timeout)
>     File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\subprocess.py", line 1401, in _communicate
>       raise TimeoutExpired(self.args, orig_timeout)
>   subprocess.TimeoutExpired: Command '['hg', 'root']' timed out after 20 seconds
>   [end of output]
</details>

Your Environment
---------

*   Operating System: windows-latest (GitHub)
*   Python Version: 3.8.10
*   Package Version: 1.2.2

Additional context
---------
- `seqeval` uses [`setuptools-scm`](https://github.com/pypa/setuptools_scm) to manage versions.
- Last week a new version of `setuptools-scm` was released and it probably broke something
- Similar issues:
  - https://github.com/pypa/setuptools_scm/issues/933
  - https://github.com/pypa/setuptools_scm/issues/861#issuecomment-1732782288
- Originally tracked here: https://github.com/deepset-ai/haystack/issues/5889

**Comment by anakin87** [comment]
https://github.com/pypa/setuptools_scm/issues/943

**Comment by anakin87** [comment]
Seems solved.
