### ISSUE TITLE
can not install in aliyun ubuntu

### ISSUE THREAD

**Issue by hotpeppeper** [chakki-works/seqeval#78]
can not install seqeval of version greater than 0.0.10
installing from the source code (via pip install -e .) report this error 

pip install seqeval
Collecting seqeval
Using cached seqeval-1.2.2.tar.gz (43 kB)
ERROR: Command errored out with exit status 1:
command: /root/anaconda3/envs/layoutxlm/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3968sdw2/seqeval_4fdb6867e5d54d70ae3b03c96a8dec1d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3968sdw2/seqeval_4fdb6867e5d54d70ae3b03c96a8dec1d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-8vwsc1dz
cwd: /tmp/pip-install-3968sdw2/seqeval_4fdb6867e5d54d70ae3b03c96a8dec1d/
Complete output (33 lines):
WARNING: The repository located at mirrors.cloud.aliyuncs.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.cloud.aliyuncs.com'.
ERROR: Could not find a version that satisfies the requirement setuptools_scm (from versions: none)
ERROR: No matching distribution found for setuptools_scm
Traceback (most recent call last):
File "/root/anaconda3/envs/layoutxlm/lib/python3.7/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
subprocess.check_call(cmd)
File "/root/anaconda3/envs/layoutxlm/lib/python3.7/subprocess.py", line 363, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/root/anaconda3/envs/layoutxlm/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpqrwh8afv', '--quiet', '--index-url', 'http://mirrors.cloud.aliyuncs.com/pypi/simple/', 'setuptools_scm']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-install-3968sdw2/seqeval_4fdb6867e5d54d70ae3b03c96a8dec1d/setup.py", line 56, in <module>
'Programming Language :: Python :: Implementation :: PyPy'
File "/root/anaconda3/envs/layoutxlm/lib/python3.7/site-packages/setuptools/__init__.py", line 152, in setup
_install_setup_requires(attrs)
File "/root/anaconda3/envs/layoutxlm/lib/python3.7/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
dist.fetch_build_eggs(dist.setup_requires)
File "/root/anaconda3/envs/layoutxlm/lib/python3.7/site-packages/setuptools/dist.py", line 689, in fetch_build_eggs
replace_conflicting=True,
File "/root/anaconda3/envs/layoutxlm/lib/python3.7/site-packages/pkg_resources/__init__.py", line 768, in resolve
replace_conflicting=replace_conflicting
File "/root/anaconda3/envs/layoutxlm/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1051, in best_match
return self.obtain(req, installer)
File "/root/anaconda3/envs/layoutxlm/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1063, in obtain
return installer(requirement)
File "/root/anaconda3/envs/layoutxlm/lib/python3.7/site-packages/setuptools/dist.py", line 745, in fetch_build_egg
return fetch_build_egg(self, req)
File "/root/anaconda3/envs/layoutxlm/lib/python3.7/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
raise DistutilsError(str(e)) from e
distutils.errors.DistutilsError: Command '['/root/anaconda3/envs/layoutxlm/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpqrwh8afv', '--quiet', '--index-url', 'http://mirrors.cloud.aliyuncs.com/pypi/simple/', 'setuptools_scm']' returned non-zero exit status 1.

*   Operating System: ubuntu
*   Python Version:  3.7
*   Package Version: 1.2.2

**Comment by terence92** [comment]
Hi, I have the same problem. I'm using a 3.7-slim python docker image.
I have already tried installing setuptools_scm first and then seqeval, but it doesn't work.
How can I solve?

**Comment by JamieVC** [comment]
These two commands work for me.
```
pip install setuptools_scm
pip install seqeval
```
